config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/sync',          to: 'pages#sync'
  get 'results/',       to: 'results#index'
  get 'agreements/:id', to: 'agreements#index'
  
  devise_for :users
  resources  :calendars, only: :create do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  require 'csv'
  belongs_to :user

  def import(file)
    specs = []
    CSV.foreach(file.path, headers: true) do |row|
      row["TA(Lecturer)"] = row["TA(Lecturer)"].match(/\w+\s\w+/).to_s

      is_teacher = row["TA(Lecturer)"] == self.user.full_name
      is_ta      = row["TA"] == self.user.full_name
      next unless is_ta || is_teacher

      spec = {
        "day": row["Day"]
      }

      spec["teacher"] = row["TA(Lecturer)"] if is_teacher
      spec["ta"]      = row["TA"] if is_ta

      specs << spec
    end

    self.update(specs: specs)
  end

  def total_income(manager = false, tot = 0)
    tot += 2400 if manager
    tot += teacher_count * 300 + ta_count * 100
  end

  def income_per_month(manager = false)
    teach_data = data_per_month("teacher")
    ta_data    = data_per_month("ta")

    teach_income = teach_data.map { |mo, days| days * 300 }
    ta_income    = ta_data.map { |mo, days| days * 100 }

    i = 0
    months_income = {}
    teach_data.each do |month, co|
      months_income[month] = teach_income[i] + ta_income[i]
      i += 1
    end

    last_month = months_income.keys.last
    months_income[last_month] += 2400 if manager
    months_income
  end

  private

  def teacher_count
    # Heroku
    self.specs.select { |spec| spec.key?("teacher") }.count
  end

  def ta_count
    self.specs.select { |spec| spec.key?("ta") }.count
  end

  def split_months
    months = self.specs.map { |hash| hash["day"].match(/,\s(?<m>\w{3})\s/)[:m] }.uniq
    months_data = {}

    months.count.times do |i|
      month = months[i]
      months_data[month] = specs.group_by do |hash|
        hash["day"].include?(months[i])
      end[true]
    end

    months_data
  end

  def data_per_month(role)
    teacher_days = {}
    split_months.each do |month, array|
      count = array.count do |hash|
        hash.key?(role)
      end
      teacher_days[month] = count
    end

    teacher_days
  end
end

app/models/client.rb
require 'nordigen-ruby'
require 'dotenv/load' if Rails.env.development?

class Client
  def create_client
    return Nordigen::NordigenClient.new(
      secret_id: ENV["SECRET_ID"],
      secret_key: ENV["SECRET_KEY"]
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :calendars, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/agreements_controller.rb
require 'securerandom'

class AgreementsController < ApplicationController
  def index
    id = params[:id]
    redirect_to '/' if id == nil
    
    client = Client.new().create_client()
    uuid = SecureRandom.uuid
    redirect_url = "https://wallet-app.herokuapp.com/results" if Rails.env.production?
    redirect_url = "http://localhost:3000/results/" if Rails.env.development?
    init = client.init_session(redirect_url: redirect_url, institution_id: id, reference_id: uuid)
    session[:requisition_id] = init["id"]
    redirect_to init["link"], allow_other_host: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :pin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :pin])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.user = current_user

    if @calendar.save
      redirect_to root_path
    else
      raise
    end
  end

  def import
    @calendar = Calendar.last
    @calendar.import(params[:file])
    
    if @calendar.save
      redirect_to root_path
    else
      raise
    end
  end

  private

  def calendar_params
    params.require(:calendar).permit(:name)
  end
end

app/controllers/pages_controller.rb
require "nordigen_ruby/api/institutions"

class PagesController < ApplicationController
  def home
    client = Client.new().create_client()
    token = client.generate_token()["access"]

    country = "NL"
    institution = Nordigen::InstitutionsApi.new(client=client)
    institution_list = institution.get_institutions(country)
    @list = institution_list.collect {|el| OpenStruct.new(el).marshal_dump }.to_json
  end

  def sync
    @calendar = Calendar.new
  end
end

app/controllers/results_controller.rb
require 'json'

class ResultsController < ApplicationController
  def index
    client = Client.new().create_client()
    requisition_id = session[:requisition_id]
    
    if !requisition_id
      raise "Requisition ID is not found. Please complete authorization with your bank"
    end
    
    requisition_data = client.requisition.get_requisition_by_id(requisition_id)
    account_id = requisition_data["accounts"][0]
    
    account = client.account(account_id)
    account_data = [{
      "metadata": account.get_metadata(),
      "balances": account.get_balances(),
      "details": account.get_details()
      # "transactions": account.get_transactions()
      }]
      
    @balance = account_data[0][:balances]
    # render :json => JSON.pretty_generate(JSON.parse(account_data.to_json))
    end
  end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/calendars/create.html.erb
<h1>Calendars#create</h1>
<p>Find me in app/views/calendars/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WalletApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/nordigen-bank-ui@1.3.0/package/src/selector.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/_nordigen_select.html.erb
<%= content_tag :div, class: "institution_list", data: {institutions: @list} do %>
<% end %>

<script src="https://unpkg.com/nordigen-bank-ui@1.3.0/package/src/selector.js"></script>
<script>
  const config = {
    redirectUrl: "https://www.nordigen.com",
    logoUrl: 'https://cdn.nordigen.com/ais/Nordigen_Logo_Black.svg',
    text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean mavdvd",
    countryFilter: true,
    styles: {
      // Primary
      fontFamily: 'https://fonts.googleapis.com/css2?family=Roboto&display=swap',
      fontSize: '15',
      backgroundColor: '#F2F2F2',
      textColor: '#222',
      // Modal
      modalTextColor: '#1B2021',
      modalBackgroundColor: '#fff',
      hoverColor: '#F1F1F1',
      // Button
      buttonColor: '#3A53EE',
      buttonTextColor: '#fff'
    }
  };

  const data = document.querySelector(".institution_list").getAttribute("data-institutions");
  institutionSelector(JSON.parse(data), "institution-modal-content", config);

  const container = document.querySelector(".institution-container");
  const observer = new MutationObserver((event) => {
    const institutions = Array.from(document.querySelectorAll(".ob-list-institution > a"));
    console.log(institutions)
    institutions.forEach((institution) => {
      institution.addEventListener("click", (e) => {
        e.preventDefault();
        const aspspId = e.currentTarget.getAttribute("data-institution");
        window.location.href = `/agreements/${aspspId}`;
      })
    })
  });

  const conf = {
    childList: true
  };
  observer.observe(container, conf);
</script>

app/views/pages/home.html.erb
<h1>Hello <%= current_user.first_name %></h1>
<%= link_to "Sync Kitt", sync_path %>
<div class="institution-content-wrapper">
    <div id="institution-modal-content">
        <header class="institution-modal-header ">
            <span class="institution-modal-close">&times;</span>
            <h2>Select your bank:</h2>
        </header>
    </div>
</div>
<%= render "nordigen_select" %>

app/views/pages/sync.html.erb
<h1>Sync (Kitt)</h1>
<%= link_to "Home", root_path %>

<%= simple_form_for @calendar do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<%= form_tag import_calendars_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag 'Import CSV' %>
<% end %>

<% unless current_user.calendars.empty? || current_user.calendars.last.specs.nil? || current_user.calendars.last.specs.empty? %>
  <h3>You will earn <%= current_user.calendars.last.total_income(manager = true) %>€</h3>

  <h3><%= current_user.calendars.last.income_per_month(manager = true) %></h3>
  <ul>
    <% current_user.calendars.last.specs.each do |spec| %>
      <li><%= spec %></li>
    <% end %>
  </ul>
<% end %>

app/views/results/index.html.erb
<h1>Data from your account</h1>
<%= @balance %>